# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: release

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: install
        run: yarn

      - name: build
        run: yarn deploy

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.VUE3_VITE_DEPLOY }}
          user_name: ${{ secrets.USER_NAME }}
          user_email: ${{ secrets.USER_EMAIL }}
          commit_message: Update Vue3 + Vite2 + TypeScript Starter

